---
openapi: 3.0.0
info:
  title: APP管理接口定义
  description: |-
    # Authentication

    <!-- ReDoc-Inject: <security-definitions> -->
  version: 2.0.0
servers:
- url: https://virtserver.swaggerhub.com/2Emma-zhou/emma/1.0
  description: SwaggerHub API Auto Mocking
- url: /open-api/appmgr/v2/
security:
- Sign: []
tags:
- name: apps
  description: APP管理
paths:
  /apps:
    get:
      tags:
      - apps
      summary: "查询APP列表,通过类型参数查询不同APP的数据,目前只支持ide,即天坊(业务设计器)APP"
      operationId: queryAppsList
      parameters:
      - name: appType
        in: query
        description: "APP类型,数组形式,通过多个类型参数查询不同APP的数据,目前只支持ide,如果传参类型不存在,则返回空列表"
        required: true
        style: form
        explode: true
        schema:
          type: array
          items:
            type: string
      - name: current
        in: query
        description: 当前页码，从1开始
        required: true
        style: form
        explode: true
        schema:
          type: integer
          default: 1
      - name: pageSize
        in: query
        description: 每页数量(默认为20，最大值为100)
        required: true
        style: form
        explode: true
        schema:
          maximum: 100
          type: integer
          default: 20
      - name: Accept-Language
        in: header
        description: 国际化语言(根据语言不同，系统编码值返回不同语言的内容)，默认为服务器操作系统语言，英文en-us，中文为zh-cn
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 请求成功后返回的内容
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: |
            错误提示
            * 100122000 APP类型参数不可以为空,{"code":100122000,"message":"APP类型参数不可以为空"}
            * 100122001 当前页码不可以为空,{"code":100122001,"message":"当前页码不可以为空"}
            * 100122002 每页数量不可以为空,{"code":100122002,"message":"每页数量不可以为空"}
            * 100122003 当前页码不可以小于1,{"code":100122003,"message":"当前页码不可以小于1"}
            * 100122004 每页数量不可以小于1,{"code":100122004,"message":"每页数量不可以小于1"}
            * 100122005 每页数量不可以大于100,{"code":100122005,"message":"每页数量不可以大于100"}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
components:
  schemas:
    ErrorCode:
      type: integer
      description: |
        请求返回的信息码
          * 400：请求失败
          * 401：权限认证失败
          * 404：未找到对应数据
          * 409：请求冲突，指定name的已经存在，不允许添加
          * 500：系统错误
      format: int64
      enum:
      - 400
      - 401
      - 404
      - 409
      - 500
    App:
      type: object
      properties:
        appId:
          type: string
          description: app id(最大长度为255)
        appType:
          type: string
          description: APP类型(最大长度为50)
        icon:
          type: string
          description: 图标(最大长度为255)
        appName:
          type: string
          description: 名称(最大长度为255)
        name:
          type: string
          description: 显示名称(最大长度为255)
        appVersion:
          type: string
          description: 版本(最大长度为255)
        vendorName:
          type: string
          description: 开发者名称(最大长度为255)
      description: APP数据
    Pagination:
      type: object
      properties:
        total:
          type: integer
          description: 总条数
          example: 1
        pageSize:
          type: integer
          description: 每页条数
          example: 20
        current:
          type: integer
          description: 当前页码
          example: 1
      description: 分页信息
    inline_response_200:
      type: object
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/App'
        pagination:
          $ref: '#/components/schemas/Pagination'
      example:
        list:
        - appId: App_9b04f4ae960146eaa3f2e82a39e757f5
          icon: /api/image/download?fileName=2021-11-02/1635867899321/App_9b04f4ae960146eaa3f2e82a39e757f5.jpg
          appName: test1
          name: test_1
          appType: ide
          appVersion: 1.0.0
          vendorName: zhangsan
        - appId: App_2df207739b1c49158eff72ec1f89dca5
          icon: /api/image/download?fileName=2021-11-02/1635867899409/App_2df207739b1c49158eff72ec1f89dca5.jpg
          appName: test2
          name: test_2
          appType: ide
          appVersion: 1.0.0
          vendorName: lisi
        pagination:
          total: 2
          pageSize: 20
          current: 1
    inline_response_400:
      type: object
      properties:
        code:
          type: integer
          description: 错误编码
          example: 100122000
        message:
          type: string
          description: 错误信息
          example: APP类型参数不可以为空
  responses:
    GeneralError:
      description: 请求失败
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorCode'
  parameters:
    acceptLanguage:
      name: Accept-Language
      in: header
      description: 国际化语言(根据语言不同，系统编码值返回不同语言的内容)，默认为服务器操作系统语言，英文en-us，中文为zh-cn
      required: false
      style: simple
      explode: false
      schema:
        type: string
  securitySchemes:
    Sign:
      type: apiKey
      name: Authorization
      in: header
